/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#include <stdint.h>


int main(void)
{
	uint32_t *pClkctrlreg = (uint32_t*) 0x5800004C;
	uint32_t *pPortBmodereg = (uint32_t*) 0x48000400;
	uint32_t *pPortBoutreg = (uint32_t*) 0x48000414;

	// 1. Enable the clock for GPIOB peripheral in the AHB2ENR
	*pClkctrlreg |= (1 << 1);

	// 2. Configure the mode of the IO pin as output
	//a. Clear 11th, 10th, 1st and 0th bits
	*pPortBmodereg &= ~(3 << 10);
	*pPortBmodereg &= ~(3 << 0);
	*pPortBmodereg &= ~(3 << 2);

	//b. Set 10th bit to 1
	*pPortBmodereg |= (1 << 10);
	//b. Set 0th bit to 1
	*pPortBmodereg |= (1 << 0);
	//b. Set 1st bit to 1
	*pPortBmodereg |= (1 << 2);

	while(1){

		// 3. Set 5th bit and 0th bith of the output data register to make I/O pin-5 as HIGH
		*pPortBoutreg |= (1 << 5);
		for(uint32_t delay = 0 ; delay < 100000 ; delay++);
		*pPortBoutreg &= ~(1 << 5);
		for(uint32_t delay = 0 ; delay < 100000 ; delay++);

		*pPortBoutreg |= (1 << 0);
		for(uint32_t delay = 0 ; delay < 100000 ; delay++);
		*pPortBoutreg &= ~(1 << 0);
		for(uint32_t delay = 0 ; delay < 100000 ; delay++);

		*pPortBoutreg |= (1 << 1);
		for(uint32_t delay = 0 ; delay < 100000 ; delay++);
		*pPortBoutreg &= ~(1 << 1);
		for(uint32_t delay = 0 ; delay < 100000 ; delay++);

		// Small human observable software delay

		//for(uint32_t delay = 0 ; delay < 10000 ; delay++);
	}


	//for(;;);
}
